---
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:
  build:
    uses: famedly/github-workflows/.github/workflows/rust.yml@main
    secrets: inherit
    with:
      extra_build_dependencies: |
        openssl
